name: "Cloud Resume Challenge CI/CD"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.0
      
      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_tenancy_ocid: ${{ secrets.TF_VAR_TENANCY_OCID }}
          TF_VAR_user_ocid: ${{ secrets.TF_VAR_USER_OCID }}
          TF_VAR_fingerprint: ${{ secrets.TF_VAR_FINGERPRINT }}
          TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
          TF_VAR_compartment_ocid: ${{ secrets.TF_VAR_COMPARTMENT_OCID }}
          TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_SSH_PUBLIC_KEY }}
          TF_VAR_private_key: ${{ secrets.OCI_PRIVATE_KEY }}
    
      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_tenancy_ocid: ${{ secrets.TF_VAR_TENANCY_OCID }}
          TF_VAR_user_ocid: ${{ secrets.TF_VAR_USER_OCID }}
          TF_VAR_fingerprint: ${{ secrets.TF_VAR_FINGERPRINT }}
          TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
          TF_VAR_compartment_ocid: ${{ secrets.TF_VAR_COMPARTMENT_OCID }}
          TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_SSH_PUBLIC_KEY }}
          TF_VAR_private_key: ${{ secrets.OCI_PRIVATE_KEY }}
  
  deploy-frontend:
    name: 'Deploy Frontend to Bucket'
    runs-on: ubuntu-latest
    needs: terraform
    env:
          TF_VAR_tenancy_ocid: ${{ secrets.TF_VAR_TENANCY_OCID }}
          TF_VAR_user_ocid: ${{ secrets.TF_VAR_USER_OCID }}
          TF_VAR_fingerprint: ${{ secrets.TF_VAR_FINGERPRINT }}
          TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
          TF_VAR_compartment_ocid: ${{ secrets.TF_VAR_COMPARTMENT_OCID }}
          TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_SSH_PUBLIC_KEY }}
          TF_VAR_private_key: ${{ secrets.OCI_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: 'Upload index.html'
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        with:
          command: 'os object put --bucket-name Cloud_Resume --namespace ${{ secrets.OCI_NAMESPACE }} --file frontend/index.html --name index.html --force' 
          silent: false

      - name: 'Upload style.css'
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        with:
          command: 'os object put --bucket-name Cloud_Resume --namespace ${{ secrets.OCI_NAMESPACE }} --file frontend/style.css --name style.css --force' 
          silent: false

      - name: 'Upload script.js'
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        with:
          command: 'os object put --bucket-name Cloud_Resume --namespace ${{ secrets.OCI_NAMESPACE }} --file frontend/script.js --name script.js --force' 
          silent: false

      - name: Verify Deployment
        run: |
          echo "‚úÖ Frontend deployed successfully!"
          echo "üåê CV URL: https://objectstorage.${{ secrets.TF_VAR_REGION }}/n${{ secrets.OCI_NAMESPACE }}/b/Cloud_Resume/o/index.html"
          


#ola